<?php return 
$arv = array(
        'language' => getLanguage(),
        'stores_id' => getStores(),
        'users_id'  => getAuth(),
        'type'  => $type,
        'title'     =>  'Sapa Vietnam Homestay & Valley Trek',
        'content'   => '<div itemprop="description"><p><span class="bold">Highlights:</span><br /><strong>Sapa Trekking Tour</strong> - Vietnam Tours: Visiting different ethnic groups such as the Tay, the Xa Pho who which cannot be found in other areas of Sapa. Even though they live close to each other, their living standard, their customs and traditions are not the same. Also enjoy beautiful landscape in Ban Ho valley.</p><p>&nbsp;</p></div><p class="bold itinerary">Day 1: Sapa - Ban Lech - Thanh Phu - Sin Chai</p>  <p class="meals">Meals: Lunch, Dinner</p>  <p>Met up at your hotel in Sapa by local guide and driver then transferred 18 km to Ban Lech village of the Red Zao. We will trek along a narrow valley downhill for 2 hour to the Ngoi Bo River, then uphill for 1 hour to Muong Bo Village at the center of Thanh Phu Commune where your lunch will be provided in a local house.<br /><br /> After lunchtime, you will trek gradually uphill to Nam Cum Village and then head to Sin Chai B village of Red Dao where the night will be spent in a local house in the village. Overnight in local homestay.<br /><br /> <em>Approx: 1-hour driving/ 6 hours walking/ 1-hour lunch.</em></p>  <p>&nbsp;</p>  <p class="bold itinerary">Day 2: Sin Chai B - Nam Than - Nam Nhiu - Nam Sai</p>  <p class="meals">Meals: Breakfast, Lunch, Dinner</p>  <p>Today&rsquo;s trek takes you through terraced rice paddies, bamboo forest and villages of the Red Zao and Tay such as Sin Chai A, Nam Than, Nam Nhiu with many stops for visiting local homes, schoools as well as for taking photos. Your lunch will be prepared and served in a local house.<br /><br /> In the afternoon, you head to Ban Sai village of Tay minority, near the center of Nam Sai Commune. Here you will walk around to explore this village and home stay overnight here in a house on stilts. Dinner will be served with Vietnamese dishes.<br /><br /> <em>Approx: 5 hours walking/ 1-hour lunch.</em></p>  <p>&nbsp;</p>  <p class="bold itinerary">Day 3: Nam Sai - My Son - Nam Toong - Sapa</p>  <p class="meals">Meals: Breakfast, Lunch</p>  <p>On the last day of the trek you will cross several suspension bridges and trek through lush rice paddy fields and stunning scenery. Once leaving Ban Sai, you will cross the river after paying visit to My Son - a village of the Xa Pho group and then follow a narrow trail uphill to Nam Keng and continue to Nam Toong, where you have lunch in a local school.<br /><br /> In the afternoon, your trek will be firstly downhill to Ban Ho village where you will have time for a swim in the river. The car will meet you there and return you to Sapa.<br /><br /> <em>Approx: 1-hour driving/ 5 hours walking/ 1 hour lunch.</em><br /> End of services!</p>  <p>&nbsp;</p>  <p class="meals"><span class="bold">Note:</span> You will go to (and from) the train station in Hanoi by yourself. Train ticket will be send by email.</p>',
        'gallery'   =>  'a:6:{i:0;s:67:"/contents/uploads/1/images/travel/Ban-Lech-Village-Sapa-Vietnam.jpg";i:1;s:67:"/contents/uploads/1/images/travel/Sin-Chai-Village-Sapa-Vietnam.jpg";i:2;s:57:"/contents/uploads/1/images/travel/Trekking-Sapa-Tours.jpg";i:3;s:60:"/contents/uploads/1/images/travel/Sapa-Trekking-Homestay.jpg";i:4;s:65:"/contents/uploads/1/images/travel/sapa-vietnam-trekking-tours.jpg";i:5;s:69:"/contents/uploads/1/images/travel/sapa-homestay-tours-days-nights.jpg";}',
        'thumbs'    =>  '',
        'created_at' => date("Y-m-d h:i:s")
        );
$data = support()->beforeCreate($arv);
$id = db("Posts::Posts",$type)->insertGetId(
    $data
);
?>