<?php
function country($select=""){

      

	$data = array(
        ['code' => 'AF', 'title' => 'Afghanistan', 'native' => 'غانستان'],
        ['code' => 'AX', 'title' => 'Åland Islands', 'native' => 'Åland'],
        ['code' => 'AL', 'title' => 'Albania', 'native' => 'Shqipëri'],
        ['code' => 'DZ', 'title' => 'Algeria', 'native' => 'الجزائر'],
        ['code' => 'AS', 'title' => 'American Samoa', 'native' => ''],
        ['code' => 'AD', 'title' => 'Andorra', 'native' => ''],
        ['code' => 'AO', 'title' => 'Angola', 'native' => ''],
        ['code' => 'AI', 'title' => 'Anguilla', 'native' => ''],
        ['code' => 'AQ', 'title' => 'Antarctica', 'native' => ''],
        ['code' => 'AG', 'title' => 'Antigua and Barbuda', 'native' => ''],
        ['code' => 'AR', 'title' => 'Argentina', 'native' => ''],
        ['code' => 'AM', 'title' => 'Armenia', 'native' => 'Հայաստան'],
        ['code' => 'AW', 'title' => 'Aruba', 'native' => ''],
        ['code' => 'AC', 'title' => 'Ascension Island', 'native' => ''],
        ['code' => 'AU', 'title' => 'Australia', 'native' => ''],
        ['code' => 'AT', 'title' => 'Austria', 'native' => 'Österreich'],
        ['code' => 'AZ', 'title' => 'Azerbaijan', 'native' => 'Azərbaycan'],
        ['code' => 'BS', 'title' => 'Bahamas', 'native' => ''],
        ['code' => 'BH', 'title' => 'Bahrain', 'native' => 'البحرين'],
        ['code' => 'BD', 'title' => 'Bangladesh', 'native' => 'বাংলাদেশ'],
        ['code' => 'BB', 'title' => 'Barbados', 'native' => ''],
        ['code' => 'BY', 'title' => 'Belarus', 'native' => 'Беларусь'],
        ['code' => 'BE', 'title' => 'Belgium', 'native' => 'België'],
        ['code' => 'BZ', 'title' => 'Belize', 'native' => ''],
        ['code' => 'BJ', 'title' => 'Benin', 'native' => 'Bénin'],
        ['code' => 'BM', 'title' => 'Bermuda', 'native' => ''],
        ['code' => 'BT', 'title' => 'Bhutan', 'native' => 'འབྲུག'],
        ['code' => 'BO', 'title' => 'Bolivia', 'native' => ''],
        ['code' => 'BA', 'title' => 'Bosnia and Herzegovina', 'native' => 'Босна и Херцеговина'],
        ['code' => 'BW', 'title' => 'Botswana', 'native' => ''],
        ['code' => 'BV', 'title' => 'Bouvet Island', 'native' => ''],
        ['code' => 'BR', 'title' => 'Brazil', 'native' => 'Brasil'],
        ['code' => 'IO', 'title' => 'British Indian Ocean Territory', 'native' => ''],
        ['code' => 'VG', 'title' => 'British Virgin Islands', 'native' => ''],
        ['code' => 'BN', 'title' => 'Brunei', 'native' => ''],
        ['code' => 'BG', 'title' => 'Bulgaria', 'native' => 'България'],
        ['code' => 'BF', 'title' => 'Burkina Faso', 'native' => ''],
        ['code' => 'BI', 'title' => 'Burundi', 'native' => 'Uburundi'],
        ['code' => 'KH', 'title' => 'Cambodia', 'native' => 'កម្ពុជា'],
        ['code' => 'CM', 'title' => 'Cameroon', 'native' => 'Cameroun'],
        ['code' => 'CA', 'title' => 'Canada', 'native' => ''],
        ['code' => 'IC', 'title' => 'Canary Islands', 'native' => 'islas Canarias'],
        ['code' => 'CV', 'title' => 'Cape Verde', 'native' => 'Kabu Verdi'],
        ['code' => 'BQ', 'title' => 'Caribbean Netherlands', 'native' => ''],
        ['code' => 'KY', 'title' => 'Cayman Islands', 'native' => ''],
        ['code' => 'CF', 'title' => 'Central African Republic', 'native' => 'République centrafricaine'],
        ['code' => 'EA', 'title' => 'Ceuta and Melilla', 'native' => 'Ceuta y Melilla'],
        ['code' => 'TD', 'title' => 'Chad', 'native' => 'Tchad'],
        ['code' => 'CL', 'title' => 'Chile', 'native' => ''],
        ['code' => 'CN', 'title' => 'China', 'native' => '中国'],
        ['code' => 'CX', 'title' => 'Christmas Island', 'native' => ''],
        ['code' => 'CP', 'title' => 'Clipperton Island', 'native' => ''],
        ['code' => 'CC', 'title' => 'Cocos (Keeling) Islands', 'native' => 'Kepulauan Cocos (Keeling)'],
        ['code' => 'CO', 'title' => 'Colombia', 'native' => ''],
        ['code' => 'KM', 'title' => 'Comoros', 'native' => 'جزر القمر'],
        ['code' => 'CD', 'title' => 'Congo (DRC)', 'native' => 'Jamhuri ya Kidemokrasia ya Kongo'],
        ['code' => 'CG', 'title' => 'Congo (Republic)', 'native' => 'Congo-Brazzaville'],
        ['code' => 'CK', 'title' => 'Cook Islands', 'native' => ''],
        ['code' => 'CR', 'title' => 'Costa Rica', 'native' => ''],
        ['code' => 'CI', 'title' => 'Côte d’Ivoire', 'native' => ''],
        ['code' => 'HR', 'title' => 'Croatia', 'native' => 'Hrvatska'],
        ['code' => 'CU', 'title' => 'Cuba', 'native' => ''],
        ['code' => 'CW', 'title' => 'Curaçao', 'native' => ''],
        ['code' => 'CY', 'title' => 'Cyprus', 'native' => 'Κύπρος'],
        ['code' => 'CZ', 'title' => 'Czech Republic', 'native' => 'Česká republika'],
        ['code' => 'DK', 'title' => 'Denmark', 'native' => 'Danmark'],
        ['code' => 'DG', 'title' => 'Diego Garcia', 'native' => ''],
        ['code' => 'DJ', 'title' => 'Djibouti', 'native' => ''],
        ['code' => 'DM', 'title' => 'Dominica', 'native' => ''],
        ['code' => 'DO', 'title' => 'Dominican Republic', 'native' => 'República Dominicana'],
        ['code' => 'EC', 'title' => 'Ecuador', 'native' => ''],
        ['code' => 'EG', 'title' => 'Egypt', 'native' => 'مصر'],
        ['code' => 'SV', 'title' => 'El Salvador', 'native' => ''],
        ['code' => 'GQ', 'title' => 'Equatorial Guinea', 'native' => 'Guinea Ecuatorial'],
        ['code' => 'ER', 'title' => 'Eritrea', 'native' => ''],
        ['code' => 'EE', 'title' => 'Estonia', 'native' => 'Eesti'],
        ['code' => 'ET', 'title' => 'Ethiopia', 'native' => ''],
        ['code' => 'FK', 'title' => 'Falkland Islands', 'native' => 'Islas Malvinas'],
        ['code' => 'FO', 'title' => 'Faroe Islands', 'native' => 'Føroyar'],
        ['code' => 'FJ', 'title' => 'Fiji', 'native' => ''],
        ['code' => 'FI', 'title' => 'Finland', 'native' => 'Suomi'],
        ['code' => 'FR', 'title' => 'France', 'native' => ''],
        ['code' => 'GF', 'title' => 'French Guiana', 'native' => 'Guyane française'],
        ['code' => 'PF', 'title' => 'French Polynesia', 'native' => 'Polynésie française'],
        ['code' => 'TF', 'title' => 'French Southern Territories', 'native' => 'Terres australes françaises'],
        ['code' => 'GA', 'title' => 'Gabon', 'native' => ''],
        ['code' => 'GM', 'title' => 'Gambia', 'native' => ''],
        ['code' => 'GE', 'title' => 'Georgia', 'native' => 'საქართველო'],
        ['code' => 'DE', 'title' => 'Germany', 'native' => 'Deutschland'],
        ['code' => 'GH', 'title' => 'Ghana', 'native' => 'Gaana'],
        ['code' => 'GI', 'title' => 'Gibraltar', 'native' => ''],
        ['code' => 'GR', 'title' => 'Greece', 'native' => 'Ελλάδα'],
        ['code' => 'GL', 'title' => 'Greenland', 'native' => 'Kalaallit Nunaat'],
        ['code' => 'GD', 'title' => 'Grenada', 'native' => ''],
        ['code' => 'GP', 'title' => 'Guadeloupe', 'native' => ''],
        ['code' => 'GU', 'title' => 'Guam', 'native' => ''],
        ['code' => 'GT', 'title' => 'Guatemala', 'native' => ''],
        ['code' => 'GG', 'title' => 'Guernsey', 'native' => ''],
        ['code' => 'GN', 'title' => 'Guinea', 'native' => 'Guinée'],
        ['code' => 'GW', 'title' => 'Guinea-Bissau', 'native' => 'Guiné Bissau'],
        ['code' => 'GY', 'title' => 'Guyana', 'native' => ''],
        ['code' => 'HT', 'title' => 'Haiti', 'native' => ''],
        ['code' => 'HM', 'title' => 'Heard & McDonald Islands', 'native' => ''],
        ['code' => 'HN', 'title' => 'Honduras', 'native' => ''],
        ['code' => 'HK', 'title' => 'Hong Kong', 'native' => '香港'],
        ['code' => 'HU', 'title' => 'Hungary', 'native' => 'Magyarország'],
        ['code' => 'IS', 'title' => 'Iceland', 'native' => 'Ísland'],
        ['code' => 'IN', 'title' => 'India', 'native' => 'भारत'],
        ['code' => 'ID', 'title' => 'Indonesia', 'native' => ''],
        ['code' => 'IR', 'title' => 'Iran', 'native' => 'ایران'],
        ['code' => 'IQ', 'title' => 'Iraq', 'native' => 'العراق'],
        ['code' => 'IE', 'title' => 'Ireland', 'native' => ''],
        ['code' => 'IM', 'title' => 'Isle of Man', 'native' => ''],
        ['code' => 'IL', 'title' => 'Israel', 'native' => 'ישראל'],
        ['code' => 'IT', 'title' => 'Italy', 'native' => 'Italia'],
        ['code' => 'JM', 'title' => 'Jamaica', 'native' => ''],
        ['code' => 'JP', 'title' => 'Japan', 'native' => '日本'],
        ['code' => 'JE', 'title' => 'Jersey', 'native' => ''],
        ['code' => 'JO', 'title' => 'Jordan', 'native' => 'الأردن'],
        ['code' => 'KZ', 'title' => 'Kazakhstan', 'native' => 'Казахстан'],
        ['code' => 'KE', 'title' => 'Kenya', 'native' => ''],
        ['code' => 'KI', 'title' => 'Kiribati', 'native' => ''],
        ['code' => 'XK', 'title' => 'Kosovo', 'native' => 'Kosovë'],
        ['code' => 'KW', 'title' => 'Kuwait', 'native' => 'الكويت'],
        ['code' => 'KG', 'title' => 'Kyrgyzstan', 'native' => 'Кыргызстан'],
        ['code' => 'LA', 'title' => 'Laos', 'native' => 'ລາວ'],
        ['code' => 'LV', 'title' => 'Latvia', 'native' => 'Latvija'],
        ['code' => 'LB', 'title' => 'Lebanon', 'native' => 'لبنان'],
        ['code' => 'LS', 'title' => 'Lesotho', 'native' => ''],
        ['code' => 'LR', 'title' => 'Liberia', 'native' => ''],
        ['code' => 'LY', 'title' => 'Libya', 'native' => 'ليبيا'],
        ['code' => 'LI', 'title' => 'Liechtenstein', 'native' => ''],
        ['code' => 'LT', 'title' => 'Lithuania', 'native' => 'Lietuva'],
        ['code' => 'LU', 'title' => 'Luxembourg', 'native' => ''],
        ['code' => 'MO', 'title' => 'Macau', 'native' => '澳門'],
        ['code' => 'MK', 'title' => 'Macedonia (FYROM)', 'native' => 'Македонија'],
        ['code' => 'MG', 'title' => 'Madagascar', 'native' => 'Madagasikara'],
        ['code' => 'MW', 'title' => 'Malawi', 'native' => ''],
        ['code' => 'MY', 'title' => 'Malaysia', 'native' => ''],
        ['code' => 'MV', 'title' => 'Maldives', 'native' => ''],
        ['code' => 'ML', 'title' => 'Mali', 'native' => ''],
        ['code' => 'MT', 'title' => 'Malta', 'native' => ''],
        ['code' => 'MH', 'title' => 'Marshall Islands', 'native' => ''],
        ['code' => 'MQ', 'title' => 'Martinique', 'native' => ''],
        ['code' => 'MR', 'title' => 'Mauritania', 'native' => 'موريتانيا'],
        ['code' => 'MU', 'title' => 'Mauritius', 'native' => 'Moris'],
        ['code' => 'YT', 'title' => 'Mayotte', 'native' => ''],
        ['code' => 'MX', 'title' => 'Mexico', 'native' => ''],
        ['code' => 'FM', 'title' => 'Micronesia', 'native' => ''],
        ['code' => 'MD', 'title' => 'Moldova', 'native' => 'Republica Moldova'],
        ['code' => 'MC', 'title' => 'Monaco', 'native' => ''],
        ['code' => 'MN', 'title' => 'Mongolia', 'native' => 'Монгол'],
        ['code' => 'ME', 'title' => 'Montenegro', 'native' => 'Crna Gora'],
        ['code' => 'MS', 'title' => 'Montserrat', 'native' => ''],
        ['code' => 'MA', 'title' => 'Morocco', 'native' => 'المغرب'],
        ['code' => 'MZ', 'title' => 'Mozambique', 'native' => 'Moçambique'],
        ['code' => 'MM', 'title' => 'Myanmar (Burma)', 'native' => 'မြန်မာ'],
        ['code' => 'NA', 'title' => 'Namibia', 'native' => 'Namibië'],
        ['code' => 'NR', 'title' => 'Nauru', 'native' => ''],
        ['code' => 'NP', 'title' => 'Nepal', 'native' => 'नेपाल'],
        ['code' => 'NL', 'title' => 'Netherlands', 'native' => 'Nederland'],
        ['code' => 'NC', 'title' => 'New Caledonia', 'native' => 'Nouvelle-Calédonie'],
        ['code' => 'NZ', 'title' => 'New Zealand', 'native' => ''],
        ['code' => 'NI', 'title' => 'Nicaragua', 'native' => ''],
        ['code' => 'NE', 'title' => 'Niger', 'native' => 'Nijar'],
        ['code' => 'NG', 'title' => 'Nigeria', 'native' => ''],
        ['code' => 'NU', 'title' => 'Niue', 'native' => ''],
        ['code' => 'NF', 'title' => 'Norfolk Island', 'native' => ''],
        ['code' => 'MP', 'title' => 'Northern Mariana Islands', 'native' => ''],
        ['code' => 'KP', 'title' => 'North Korea', 'native' => '조선 민주주의 인민 공화국'],
        ['code' => 'NO', 'title' => 'Norway', 'native' => 'Norge'],
        ['code' => 'OM', 'title' => 'Oman', 'native' => 'عُمان'],
        ['code' => 'PK', 'title' => 'Pakistan', 'native' => 'پاکستان'],
        ['code' => 'PW', 'title' => 'Palau', 'native' => ''],
        ['code' => 'PS', 'title' => 'Palestine', 'native' => 'فلسطين'],
        ['code' => 'PA', 'title' => 'Panama', 'native' => ''],
        ['code' => 'PG', 'title' => 'Papua New Guinea', 'native' => ''],
        ['code' => 'PY', 'title' => 'Paraguay', 'native' => ''],
        ['code' => 'PE', 'title' => 'Peru', 'native' => 'Perú'],
        ['code' => 'PH', 'title' => 'Philippines', 'native' => ''],
        ['code' => 'PN', 'title' => 'Pitcairn Islands', 'native' => ''],
        ['code' => 'PL', 'title' => 'Poland', 'native' => 'Polska'],
        ['code' => 'PT', 'title' => 'Portugal', 'native' => ''],
        ['code' => 'PR', 'title' => 'Puerto Rico', 'native' => ''],
        ['code' => 'QA', 'title' => 'Qatar', 'native' => 'قطر'],
        ['code' => 'RE', 'title' => 'Réunion', 'native' => 'La Réunion'],
        ['code' => 'RO', 'title' => 'Romania', 'native' => 'România'],
        ['code' => 'RU', 'title' => 'Russia', 'native' => 'Россия'],
        ['code' => 'RW', 'title' => 'Rwanda', 'native' => ''],
        ['code' => 'BL', 'title' => 'Saint Barthélemy', 'native' => 'Saint-Barthélemy'],
        ['code' => 'SH', 'title' => 'Saint Helena', 'native' => ''],
        ['code' => 'KN', 'title' => 'Saint Kitts and Nevis', 'native' => ''],
        ['code' => 'LC', 'title' => 'Saint Lucia', 'native' => ''],
        ['code' => 'MF', 'title' => 'Saint Martin', 'native' => ''],
        ['code' => 'PM', 'title' => 'Saint Pierre and Miquelon', 'native' => 'Saint-Pierre-et-Miquelon'],
        ['code' => 'WS', 'title' => 'Samoa', 'native' => ''],
        ['code' => 'SM', 'title' => 'San Marino', 'native' => ''],
        ['code' => 'ST', 'title' => 'São Tomé and Príncipe', 'native' => 'São Tomé e Príncipe'],
        ['code' => 'SA', 'title' => 'Saudi Arabia', 'native' => 'المملكة العربية السعودية'],
        ['code' => 'SN', 'title' => 'Senegal', 'native' => 'Sénégal'],
        ['code' => 'RS', 'title' => 'Serbia', 'native' => 'Србија'],
        ['code' => 'SC', 'title' => 'Seychelles', 'native' => ''],
        ['code' => 'SL', 'title' => 'Sierra Leone', 'native' => ''],
        ['code' => 'SG', 'title' => 'Singapore', 'native' => ''],
        ['code' => 'SX', 'title' => 'Sint Maarten', 'native' => ''],
        ['code' => 'SK', 'title' => 'Slovakia', 'native' => 'Slovensko'],
        ['code' => 'SI', 'title' => 'Slovenia', 'native' => 'Slovenija'],
        ['code' => 'SB', 'title' => 'Solomon Islands', 'native' => ''],
        ['code' => 'SO', 'title' => 'Somalia', 'native' => 'Soomaaliya'],
        ['code' => 'ZA', 'title' => 'South Africa', 'native' => ''],
        ['code' => 'GS', 'title' => 'South Georgia & South Sandwich Islands', 'native' => ''],
        ['code' => 'KR', 'title' => 'South Korea', 'native' => '대한민국'],
        ['code' => 'SS', 'title' => 'South Sudan', 'native' => 'جنوب السودان'],
        ['code' => 'ES', 'title' => 'Spain', 'native' => 'España'],
        ['code' => 'LK', 'title' => 'Sri Lanka', 'native' => 'ශ්‍රී ලංකාව'],
        ['code' => 'VC', 'title' => 'St. Vincent & Grenadines', 'native' => ''],
        ['code' => 'SD', 'title' => 'Sudan', 'native' => 'السودان'],
        ['code' => 'SR', 'title' => 'Suriname', 'native' => ''],
        ['code' => 'SJ', 'title' => 'Svalbard and Jan Mayen', 'native' => 'Svalbard og Jan Mayen'],
        ['code' => 'SZ', 'title' => 'Swaziland', 'native' => ''],
        ['code' => 'SE', 'title' => 'Sweden', 'native' => 'Sverige'],
        ['code' => 'CH', 'title' => 'Switzerland', 'native' => 'Schweiz'],
        ['code' => 'SY', 'title' => 'Syria', 'native' => 'سوريا'],
        ['code' => 'TW', 'title' => 'Taiwan', 'native' => '台灣'],
        ['code' => 'TJ', 'title' => 'Tajikistan', 'native' => ''],
        ['code' => 'TZ', 'title' => 'Tanzania', 'native' => ''],
        ['code' => 'TH', 'title' => 'Thailand', 'native' => 'ไทย'],
        ['code' => 'TL', 'title' => 'Timor-Leste', 'native' => ''],
        ['code' => 'TG', 'title' => 'Togo', 'native' => ''],
        ['code' => 'TK', 'title' => 'Tokelau', 'native' => ''],
        ['code' => 'TO', 'title' => 'Tonga', 'native' => ''],
        ['code' => 'TT', 'title' => 'Trinidad and Tobago', 'native' => ''],
        ['code' => 'TA', 'title' => 'Tristan da Cunha', 'native' => ''],
        ['code' => 'TN', 'title' => 'Tunisia', 'native' => 'تونس'],
        ['code' => 'TR', 'title' => 'Turkey', 'native' => 'Türkiye'],
        ['code' => 'TM', 'title' => 'Turkmenistan', 'native' => ''],
        ['code' => 'TC', 'title' => 'Turks and Caicos Islands', 'native' => ''],
        ['code' => 'TV', 'title' => 'Tuvalu', 'native' => ''],
        ['code' => 'UM', 'title' => 'U.S. Outlying Islands', 'native' => ''],
        ['code' => 'VI', 'title' => 'U.S. Virgin Islands', 'native' => ''],
        ['code' => 'UG', 'title' => 'Uganda', 'native' => ''],
        ['code' => 'UA', 'title' => 'Ukraine', 'native' => 'Україна'],
        ['code' => 'AE', 'title' => 'United Arab Emirates', 'native' => 'الإمارات العربية المتحدة'],
        ['code' => 'GB', 'title' => 'United Kingdom', 'native' => ''],
        ['code' => 'US', 'title' => 'United States', 'native' => ''],
        ['code' => 'UY', 'title' => 'Uruguay', 'native' => ''],
        ['code' => 'UZ', 'title' => 'Uzbekistan', 'native' => 'Oʻzbekiston'],
        ['code' => 'VU', 'title' => 'Vanuatu', 'native' => ''],
        ['code' => 'VA', 'title' => 'Vatican City', 'native' => 'Città del Vaticano'],
        ['code' => 'VE', 'title' => 'Venezuela', 'native' => ''],
        ['code' => 'VN', 'title' => 'Vietnam', 'native' => 'Việt Nam'],
        ['code' => 'WF', 'title' => 'Wallis and Futuna', 'native' => ''],
        ['code' => 'EH', 'title' => 'Western Sahara', 'native' => 'الصحراء الغربية'],
        ['code' => 'YE', 'title' => 'Yemen', 'native' => 'اليمن'],
        ['code' => 'ZM', 'title' => 'Zambia', 'native' => ''],
        ['code' => 'ZW', 'title' => 'Zimbabwe', 'native' => '']
    );
	foreach ($data as $key => $value) {
		echo '<option value="'.$value["code"].'" '.(strtolower($select) == strtolower($value["code"]) ? "selected" : "").'>'.$value["title"].($value["native"] ? '( '.$value["native"].' )' : "").'</option>';
	}
}






function detect_city($ip) {
        
        $default = 'UNKNOWN';

        if (!is_string($ip) || strlen($ip) < 1 || $ip == '127.0.0.1' || $ip == 'localhost')
            $ip = '8.8.8.8';

        $curlopt_useragent = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6 (.NET CLR 3.5.30729)';
        
        $url = 'http://ipinfodb.com/ip_locator.php?ip=' . urlencode($ip);
        $ch = curl_init();
        
        $curl_opt = array(
            CURLOPT_FOLLOWLOCATION  => 1,
            CURLOPT_HEADER      => 0,
            CURLOPT_RETURNTRANSFER  => 1,
            CURLOPT_USERAGENT   => $curlopt_useragent,
            CURLOPT_URL       => $url,
            CURLOPT_TIMEOUT         => 1,
            CURLOPT_REFERER         => 'http://' . $_SERVER['HTTP_HOST'],
        );
        
        curl_setopt_array($ch, $curl_opt);
        
        $content = curl_exec($ch);
        
        if (!is_null($curl_info)) {
            $curl_info = curl_getinfo($ch);
        }
        
        curl_close($ch);
        
        if ( preg_match('{<li>City : ([^<]*)</li>}i', $content, $regs) )  {
            $city = $regs[1];
        }
        if ( preg_match('{<li>State/Province : ([^<]*)</li>}i', $content, $regs) )  {
            $state = $regs[1];
        }

        if( $city!='' && $state!='' ){
          $location = $city . ', ' . $state;
          return $location;
        }else{
          return $default; 
        }
        
}

?>