<?php return 
array (
  'sitename' => 'Demo Lumen Site API',
  'description' => 'seo, marketing, laravel, cms, crm, ERP, php, linux, hosting',
  'keyword' => 'seo, marketing, laravel, cms, crm, ERP, php, linux, hosting',
  'google_analytic' => 'UA-12078642-3',
  'language' => 'vn',
  'templates' => 'shops',
  'templates_admin' => 'default',
  'page_default' => '',
  'popup_id' => '',
  'email' => 'thietkewebvip@gmail.com',
  'hotline' => '0903908078',
  'hotline_1' => '',
  'hotline_2' => '',
  'time_zone' => 'Asia/Ho_Chi_Minh',
  'time_short_format' => 'd-m-Y',
  'time_long_format' => 'D M Y h:i:s A',
  'address' => 'LK 10, CC Khang Gia, P14, Phan Huy Ich, Go Vap, HCM',
  'country' => 'VN',
  'city' => 'HCM',
  'stase' => '',
  'opendor' => '7 - 5h PM / 2 - 6',
  'header_tags' => '',
  'footer_tags' => '',
  'users_can_register' => 'yes',
  'users_register_welcome' => 'yes',
  'users_register_action' => '',
  'users_register_groups' => 'none',
  'smtp_server' => 'smtp.gmail.com',
  'smtp_username' => 'contact@thietkewebvip.com',
  'smtp_password' => 'anhkhoa',
  'smtp_port' => '587',
  'smtp_encryption' => 'tls',
  'logo' => '/contents/uploads/1/images/vtn-logo.png',
  'icons' => '',
  'page_editter' => '',
  'google_api' => 'AIzaSyBGKSEZZtmH_hDKwTPhCRnPppD9mTQ_bok',
  'social' => 
  array (
    'private' => '',
    'android' => '',
    'twitter' => '',
    'youtube' => '',
    'youtube-play' => '',
    'whatsapp' => '',
  ),
  'comments_by' => 'facebook',
)
?>